// Generated by CoffeeScript 1.6.2
(function() {
  var LocalObject,
    __slice = [].slice;

  LocalObject = (function() {
    LocalObject.prototype.neighbor = null;

    function LocalObject(guid, neighbor) {
      this.guid = guid;
      this.neighbor = neighbor;
    }

    LocalObject.prototype.emit = function() {
      var _ref;

      return (_ref = this.neighbor).dispatchRemoteEvent.apply(_ref, [this.guid].concat(__slice.call(arguments)));
    };

    LocalObject.prototype.destroy = function() {};

    return LocalObject;

  })();

  exports.LocalObject = LocalObject;

}).call(this);
