// Generated by CoffeeScript 1.6.2
(function() {
  var EventEmitter, RemoteObject, utils,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  utils = require('./utils');

  EventEmitter = require('events').EventEmitter;

  RemoteObject = (function(_super) {
    __extends(RemoteObject, _super);

    RemoteObject.prototype.neighbor = null;

    function RemoteObject(neighbor, callback) {
      this.neighbor = neighbor;
      this.guid = utils.guid();
      this.neighbor.createRemoteObject(this, callback);
    }

    RemoteObject.prototype.destroy = function() {
      return this.neighbor.destroyRemoteObject(this);
    };

    RemoteObject.prototype.call = function() {
      var _ref;

      return (_ref = this.neighbor).callRemoteFunction.apply(_ref, [this.guid].concat(__slice.call(arguments)));
    };

    return RemoteObject;

  })(EventEmitter);

  exports.RemoteObject = RemoteObject;

}).call(this);
